name: CI/CD Frontend

on:
  push:
    branches: ['main', 'development']
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build da imagem (teste local)
        run: docker build -t frontend .

  push-image:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Definir repo e tag
        id: vars
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "repo=${{ secrets.DOCKER_USERNAME }}/frontend" >> $GITHUB_OUTPUT
            echo "tag=latest" >> $GITHUB_OUTPUT

          elif [ "${{ github.ref_name }}" = "development" ]; then
            echo "repo=${{ secrets.DOCKER_USERNAME }}/frontend" >> $GITHUB_OUTPUT
            echo "tag=dev" >> $GITHUB_OUTPUT

          else
            echo "repo=${{ secrets.DOCKER_USERNAME }}/frontend" >> $GITHUB_OUTPUT
            echo "tag=pr" >> $GITHUB_OUTPUT
          fi

      - name: Build imagem final
        run: docker build -t ${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.tag }} .

      - name: Push imagem
        run: docker push ${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.tag }}
